### PR TITLE
adds first version of site search

### PR DESCRIPTION
**Pull request by derekeder**
Creates a new page that allows for searching on titles, dates, categories, tags and descriptions for all `posts` on the Chi Hack Night website:

chn-search

Overview
* Implements #320 
* Hides the projects top nav (its become pretty stale) and adds a search button

### CODE REVIEW

**Review by easherma — CHANGES_REQUESTED** [review]
This is a great start! Thanks for putting it together. 

We should see if we can have @Sluker  test this PR, esp since the search was his idea. 

Some other thoughts. 

* The format of the results could be improved. Sections can be labeled, and all or most of the search result for a line should be a link to that result. Happy to help with this ASAP

* I'll have to look at the search library more, but does it by default only return x results or return all of them? It appears to return a limited amount ( compare search to search on the events page ). 

* It would be nice to flesh out 'no results found' perhaps with prompts to search again or have links to Blogs, Events (which has its own search).

* Having the search box be so long looks kinda weird, but fine. I wonder if there is a way to integrate search onto the homepage, though that may not be desired behavior.

**Comment by shua123** [comment]
Yeah @easherma. I noticed that too about limited # of results.  If I search "school" I don't get the older events I get if I [search school on the events page](https://deploy-preview-322--chihacknight-website.netlify.app/events/index.html#/?search=school).

How difficult would it be to have url param for the search query?

**Comment by derekeder** [comment]
@easherma in response to your comments:

* I ran this by Steve Luker. His comment: "I found chi safe path with 'disability' and 'accessible', but not  'accessibility'. but its definitely better"
* Format of search results: The search mechanism is relatively simple and doesn't have a ton of customization. We are somewhat limited with what is possible with Jekyll and I do not want to invest in anything heavy like Solr, elastisearch, etc. Google Site search is an option, but I'd prefer to not rely on a third party service. However, if you would like to [look at the code](https://github.com/christian-fei/Simple-Jekyll-Search) and suggest changes in this PR, I would welcome it.
* Number of search results: Yes, it limits the results to 10 by default. We can override this, but the higher the limit, the slower the response. I bumped this up to 20, which seems like it might do the trick.
* 'No results found': happy to get your suggested changes for this
* We can change the size of the search box, but the developer advises against adding it to the site nav or home page for performance reasons. We are loading a large `json` file that is an index of ~500 pages, which would impact our page load

@shua123 yes we probably could add a url param for the search term. I don't think its blocking this PR, so please open an issue if you'd like

**Comment by derekeder** [comment]
@shua123 @easherma anything blocking us from pulling this in?

**Comment by easherma** [comment]
I'd say lets go for it!

**Comment by shua123** [comment]
I would like it to have a little more context/instruction and disclose the max search result setting. It is still very easy to miss search results because of the result limit and its important we explain that.

**Comment by shua123** [comment]
Lighthouse identified 2 accessibility issues:

1. The search input box does not have a label
2. The search icon in the navbar: "Links do not have a discernible name. Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users."

**Comment by derekeder** [comment]
@shua123 thanks for pointing out and adding the accessibility changes.

I caught this up to the `production` branch and added a note about only showing the top 20 results.

Let me know if this looks good to you now and we can bring it in.

**Comment by shua123** [comment]
Looks good

**Pull request merged**
