### PR TITLE
Added myself to the PBR page. 

### PR DESCRIPTION
**Pull request by zscore**
Got impatient trying to get Jekyll and Ruby to work properly so this is untested.

### CODE REVIEW

**Comment by derekeder** [comment]
Looks good! Merging

**Comment by derekeder** [comment]
Hey FYI had to make some edits: https://github.com/chihacknight/chihacknight.org/commit/768f8c7eaf3c8df76bdb977a1ed3b13112f80254

Extra table column was added. Also the picture was too large and needed to be recropped as a square.

**Comment by zscore** [comment]
cool thanks so much! BTW is there a docker image or something that I could
use to preview the site with Jekyll?

-sent from mobile device.

**Comment by derekeder** [comment]
Hmm i dunno. Maybe lets ask folks in the #tech channel

**Pull request merged**
