### PR TITLE
[WIP] Netlify CMS

### PR DESCRIPTION
**Pull request by easherma**
this is out of date, stubbing for now

### CODE REVIEW

**Comment by easherma** [comment]
related to #184

**Comment by derekeder** [comment]
updated the title to indicate this is a work in progress (WIP)

**Comment by derekeder** [comment]
@easherma in looking through this, the code changes seem to be mostly related to using the Netlify CMS. I think this is still a good idea, but wanted to keep it separate from changing our hosting provider.

Now that #184 is done, do you want to rebase this with master and get it ready to merge in?

**Comment by easherma** [comment]
Totes

**Comment by easherma** [comment]
closing in favor of https://github.com/chihacknight/chihacknight.org/pull/194

**Pull request closed without merging**
