### PR TITLE
Update Code Clinic blurb and add Hillel Wayne

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by derekeder** [comment]
Looks good! I'll crop the image and deploy.

**Comment by derekeder** [comment]
Deployed. Say hello! https://chihacknight.org/breakouts.html

**Comment by kfogel** [comment]
Oh!  Sorry, @derekeder, I could have cropped the image -- next time feel free to just bounce it back to me, if there's something I didn't think of.  Thanks for fixing it and deploying.

**Comment by derekeder** [comment]
No worries! I should probably add clearer contribution instructions.

**Pull request merged**
