### PR TITLE
Add Tori Kraft to Code Clinic breakout group

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by derekeder** [comment]
All right - another one!

**Comment by derekeder** [comment]
also, should we keep Rene if he won't be able to attend Chi Hack Night for a while? We can always add him back. My concern is the list is getting kinda long!

**Comment by kfogel** [comment]
On May 14, 2016 1:32 PM, "Derek Eder" <notifications@github.com> wrote:
>
> also, should we keep Rene if he won't be able to attend Chi Hack Night
for a while? We can always add him back. My concern is the list is getting
kinda long!

I was thinking about that, yeah, but wanted to ask him first. Anyway, we'll
face the same length problem as others join (one more in the pipeline right
now), so will need to think of a solution anyway.  Esp with Code Clinic,
having the photos is useful.

-K

**Comment by derekeder** [comment]
I could also handle it in the layout. 2 photos per row

On Sun, May 15, 2016 at 8:13 AM, Karl Fogel <notifications@github.com>
wrote:

> On May 14, 2016 1:32 PM, "Derek Eder" <notifications@github.com> wrote:
> >
> > also, should we keep Rene if he won't be able to attend Chi Hack Night
> for a while? We can always add him back. My concern is the list is getting
> kinda long!
>
> I was thinking about that, yeah, but wanted to ask him first. Anyway, we'll
> face the same length problem as others join (one more in the pipeline right
> now), so will need to think of a solution anyway. Esp with Code Clinic,
> having the photos is useful.
>
> -K
>
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/chihacknight/chihacknight.org/pull/104#issuecomment-219285082>
>



-- 
Derek Eder
@derekeder <https://twitter.com/#!/derekeder>
derek.eder@gmail.com
derekeder.com

**Pull request merged**
